-- @l0 L0-002 · @req CORA-02/REQ-1 · @acr ACR-1.2
ALTER TABLE volcado ADD COLUMN IF NOT EXISTS audio_url TEXT;
ALTER TABLE volcado ADD COLUMN IF NOT EXISTS audio_bytes INTEGER;
ALTER TABLE volcado ADD COLUMN IF NOT EXISTS duracion_seg INTEGER;
ALTER TABLE volcado ADD COLUMN IF NOT EXISTS fuente TEXT DEFAULT $$texto$$;
ALTER TABLE volcado ADD COLUMN IF NOT EXISTS pulido_aplicado BOOLEAN DEFAULT false;
